/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_3d_acados_mpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[36] = {-7.0699999999999996e-01, 7.0699999999999996e-01, 0., -5.0999999999999997e-02, -5.0999999999999997e-02, 1.6700000000000001e-01, -7.0699999999999996e-01, -7.0699999999999996e-01, 0., 5.0999999999999997e-02, 5.0999999999999997e-02, -1.6700000000000001e-01, 7.0699999999999996e-01, 7.0699999999999996e-01, 0., -5.0999999999999997e-02, -5.0999999999999997e-02, -1.7499999999999999e-01, 7.0699999999999996e-01, -7.0699999999999996e-01, 0., 5.0999999999999997e-02, 5.0999999999999997e-02, 1.7499999999999999e-01, 0., 0., -1., 1.1100000000000000e-01, -2.0000000000000000e-03, 0., 0., 0., -1., -1.1100000000000000e-01, 2.0000000000000000e-03, 0.};

/* quad_3d_acados_mpc_expl_ode_fun:(i0[12],i1[6],i2[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+6, *w1=w+9, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+20, *w11=w+23, *w12=w+26, *w13=w+29, *w14=w+38, *w15=w+47, *w16=w+53, *w17=w+89, w18, w19;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #6: @3 = (@3*@5) */
  w3 *= w5;
  /* #7: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #8: @6 = @1[0] */
  for (rr=(&w6), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #9: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #10: @5 = (@5*@7) */
  w5 *= w7;
  /* #11: @7 = sin(@4) */
  w7 = sin( w4 );
  /* #12: @5 = (@5*@7) */
  w5 *= w7;
  /* #13: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #14: @8 = sin(@2) */
  w8 = sin( w2 );
  /* #15: @7 = (@7*@8) */
  w7 *= w8;
  /* #16: @5 = (@5-@7) */
  w5 -= w7;
  /* #17: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #18: @8 = sin(@2) */
  w8 = sin( w2 );
  /* #19: @7 = (@7*@8) */
  w7 *= w8;
  /* #20: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #21: @9 = cos(@2) */
  w9 = cos( w2 );
  /* #22: @8 = (@8*@9) */
  w8 *= w9;
  /* #23: @9 = sin(@4) */
  w9 = sin( w4 );
  /* #24: @8 = (@8*@9) */
  w8 *= w9;
  /* #25: @7 = (@7+@8) */
  w7 += w8;
  /* #26: @10 = horzcat(@3, @5, @7) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #27: @10 = @10' */
  /* #28: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #29: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #30: @3 = (@3*@5) */
  w3 *= w5;
  /* #31: @5 = cos(@6) */
  w5 = cos( w6 );
  /* #32: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #33: @5 = (@5*@7) */
  w5 *= w7;
  /* #34: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #35: @8 = sin(@2) */
  w8 = sin( w2 );
  /* #36: @7 = (@7*@8) */
  w7 *= w8;
  /* #37: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #38: @7 = (@7*@8) */
  w7 *= w8;
  /* #39: @5 = (@5+@7) */
  w5 += w7;
  /* #40: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #41: @8 = sin(@2) */
  w8 = sin( w2 );
  /* #42: @7 = (@7*@8) */
  w7 *= w8;
  /* #43: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #44: @7 = (@7*@8) */
  w7 *= w8;
  /* #45: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #46: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #47: @2 = (@2*@8) */
  w2 *= w8;
  /* #48: @7 = (@7-@2) */
  w7 -= w2;
  /* #49: @11 = horzcat(@3, @5, @7) */
  rr=w11;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #50: @11 = @11' */
  /* #51: @3 = sin(@4) */
  w3 = sin( w4 );
  /* #52: @3 = (-@3) */
  w3 = (- w3 );
  /* #53: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #54: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #55: @5 = (@5*@7) */
  w5 *= w7;
  /* #56: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #57: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #58: @6 = (@6*@4) */
  w6 *= w4;
  /* #59: @12 = horzcat(@3, @5, @6) */
  rr=w12;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w6;
  /* #60: @12 = @12' */
  /* #61: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #62: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #63: @10 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w10);
  /* #64: @0 = mac(@14,@10,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #65: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #66: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #67: @3 = 1 */
  w3 = 1.;
  /* #68: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #69: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #70: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #71: @7 = tan(@4) */
  w7 = tan( w4 );
  /* #72: @6 = (@6*@7) */
  w6 *= w7;
  /* #73: @7 = cos(@5) */
  w7 = cos( w5 );
  /* #74: @2 = tan(@4) */
  w2 = tan( w4 );
  /* #75: @7 = (@7*@2) */
  w7 *= w2;
  /* #76: @1 = horzcat(@3, @6, @7) */
  rr=w1;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w7;
  /* #77: @1 = @1' */
  /* #78: @3 = 0 */
  w3 = 0.;
  /* #79: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #80: @7 = sin(@5) */
  w7 = sin( w5 );
  /* #81: @7 = (-@7) */
  w7 = (- w7 );
  /* #82: @11 = horzcat(@3, @6, @7) */
  rr=w11;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w7;
  /* #83: @11 = @11' */
  /* #84: @3 = 0 */
  w3 = 0.;
  /* #85: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #86: @7 = cos(@4) */
  w7 = cos( w4 );
  /* #87: @6 = (@6/@7) */
  w6 /= w7;
  /* #88: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #89: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #90: @5 = (@5/@4) */
  w5 /= w4;
  /* #91: @12 = horzcat(@3, @6, @5) */
  rr=w12;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w5;
  /* #92: @12 = @12' */
  /* #93: @14 = horzcat(@1, @11, @12) */
  rr=w14;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #94: @13 = @14' */
  for (i=0, rr=w13, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #95: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 3, w1);
  /* #96: @0 = mac(@13,@1,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #97: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #98: @3 = 0.0492611 */
  w3 = 4.9261083743842360e-02;
  /* #99: @15 = zeros(6x1) */
  casadi_clear(w15, 6);
  /* #100: @16 = 
  [[-0.707, -0.707, 0.707, 0.707, -0, -0], 
   [0.707, -0.707, 0.707, -0.707, -0, -0], 
   [-0, -0, -0, -0, -1, -1], 
   [-0.051, 0.051, -0.051, 0.051, 0.111, -0.111], 
   [-0.051, 0.051, -0.051, 0.051, -0.002, 0.002], 
   [0.167, -0.167, -0.175, 0.175, -0, -0]] */
  casadi_copy(casadi_c0, 36, w16);
  /* #101: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #102: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #103: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #104: @7 = input[1][3] */
  w7 = arg[1] ? arg[1][3] : 0;
  /* #105: @2 = input[1][4] */
  w2 = arg[1] ? arg[1][4] : 0;
  /* #106: @8 = input[1][5] */
  w8 = arg[1] ? arg[1][5] : 0;
  /* #107: @17 = vertcat(@6, @5, @4, @7, @2, @8) */
  rr=w17;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w2;
  *rr++ = w8;
  /* #108: @15 = mac(@16,@17,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w17+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #109: @6 = @15[0] */
  for (rr=(&w6), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #110: @5 = 14.8 */
  w5 = 1.4800000000000001e+01;
  /* #111: @4 = @10[2] */
  for (rr=(&w4), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #112: @5 = (@5*@4) */
  w5 *= w4;
  /* #113: @7 = -14.57 */
  w7 = -1.4570000000000000e+01;
  /* #114: @7 = (@7*@4) */
  w7 *= w4;
  /* #115: @5 = (@5-@7) */
  w5 -= w7;
  /* #116: @7 = @1[1] */
  for (rr=(&w7), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #117: @5 = (@5*@7) */
  w5 *= w7;
  /* #118: @6 = (@6-@5) */
  w6 -= w5;
  /* #119: @5 = -14.8 */
  w5 = -1.4800000000000001e+01;
  /* #120: @2 = @10[1] */
  for (rr=(&w2), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #121: @5 = (@5*@2) */
  w5 *= w2;
  /* #122: @8 = -12.7 */
  w8 = -1.2699999999999999e+01;
  /* #123: @8 = (@8*@2) */
  w8 *= w2;
  /* #124: @5 = (@5+@8) */
  w5 += w8;
  /* #125: @8 = @1[2] */
  for (rr=(&w8), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #126: @5 = (@5*@8) */
  w5 *= w8;
  /* #127: @6 = (@6-@5) */
  w6 -= w5;
  /* #128: @5 = -4.03 */
  w5 = -4.0300000000000002e+00;
  /* #129: @9 = -18.18 */
  w9 = -1.8180000000000000e+01;
  /* #130: @18 = @10[0] */
  for (rr=(&w18), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #131: @19 = fabs(@18) */
  w19 = casadi_fabs( w18 );
  /* #132: @9 = (@9*@19) */
  w9 *= w19;
  /* #133: @5 = (@5+@9) */
  w5 += w9;
  /* #134: @5 = (@5*@18) */
  w5 *= w18;
  /* #135: @6 = (@6+@5) */
  w6 += w5;
  /* #136: @3 = (@3*@6) */
  w3 *= w6;
  /* #137: output[0][2] = @3 */
  if (res[0]) res[0][6] = w3;
  /* #138: @3 = 0.0363636 */
  w3 = 3.6363636363636362e-02;
  /* #139: @6 = @15[1] */
  for (rr=(&w6), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #140: @5 = -14.8 */
  w5 = -1.4800000000000001e+01;
  /* #141: @5 = (@5*@4) */
  w5 *= w4;
  /* #142: @9 = -14.57 */
  w9 = -1.4570000000000000e+01;
  /* #143: @9 = (@9*@4) */
  w9 *= w4;
  /* #144: @5 = (@5+@9) */
  w5 += w9;
  /* #145: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #146: @5 = (@5*@9) */
  w5 *= w9;
  /* #147: @6 = (@6-@5) */
  w6 -= w5;
  /* #148: @5 = 14.8 */
  w5 = 1.4800000000000001e+01;
  /* #149: @5 = (@5*@18) */
  w5 *= w18;
  /* #150: @19 = -5.5 */
  w19 = -5.5000000000000000e+00;
  /* #151: @19 = (@19*@18) */
  w19 *= w18;
  /* #152: @5 = (@5-@19) */
  w5 -= w19;
  /* #153: @5 = (@5*@8) */
  w5 *= w8;
  /* #154: @6 = (@6-@5) */
  w6 -= w5;
  /* #155: @5 = -6.22 */
  w5 = -6.2199999999999998e+00;
  /* #156: @8 = -21.66 */
  w8 = -2.1660000000000000e+01;
  /* #157: @19 = fabs(@2) */
  w19 = casadi_fabs( w2 );
  /* #158: @8 = (@8*@19) */
  w8 *= w19;
  /* #159: @5 = (@5+@8) */
  w5 += w8;
  /* #160: @5 = (@5*@2) */
  w5 *= w2;
  /* #161: @6 = (@6+@5) */
  w6 += w5;
  /* #162: @3 = (@3*@6) */
  w3 *= w6;
  /* #163: output[0][3] = @3 */
  if (res[0]) res[0][7] = w3;
  /* #164: @3 = 0.0340483 */
  w3 = 3.4048348655090224e-02;
  /* #165: @6 = 145.04 */
  w6 = 1.4504000000000002e+02;
  /* #166: @5 = @15[2] */
  for (rr=(&w5), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #167: @8 = 14.8 */
  w8 = 1.4800000000000001e+01;
  /* #168: @8 = (@8*@2) */
  w8 *= w2;
  /* #169: @19 = -12.7 */
  w19 = -1.2699999999999999e+01;
  /* #170: @19 = (@19*@2) */
  w19 *= w2;
  /* #171: @8 = (@8-@19) */
  w8 -= w19;
  /* #172: @8 = (@8*@9) */
  w8 *= w9;
  /* #173: @5 = (@5-@8) */
  w5 -= w8;
  /* #174: @8 = -14.8 */
  w8 = -1.4800000000000001e+01;
  /* #175: @8 = (@8*@18) */
  w8 *= w18;
  /* #176: @9 = -5.5 */
  w9 = -5.5000000000000000e+00;
  /* #177: @9 = (@9*@18) */
  w9 *= w18;
  /* #178: @8 = (@8+@9) */
  w8 += w9;
  /* #179: @8 = (@8*@7) */
  w8 *= w7;
  /* #180: @5 = (@5-@8) */
  w5 -= w8;
  /* #181: @8 = -5.18 */
  w8 = -5.1799999999999997e+00;
  /* #182: @7 = -36.99 */
  w7 = -3.6990000000000002e+01;
  /* #183: @9 = fabs(@4) */
  w9 = casadi_fabs( w4 );
  /* #184: @7 = (@7*@9) */
  w7 *= w9;
  /* #185: @8 = (@8+@7) */
  w8 += w7;
  /* #186: @8 = (@8*@4) */
  w8 *= w4;
  /* #187: @5 = (@5+@8) */
  w5 += w8;
  /* #188: @8 = 143.04 */
  w8 = 1.4304000000000002e+02;
  /* #189: @5 = (@5-@8) */
  w5 -= w8;
  /* #190: @6 = (@6+@5) */
  w6 += w5;
  /* #191: @3 = (@3*@6) */
  w3 *= w6;
  /* #192: output[0][4] = @3 */
  if (res[0]) res[0][8] = w3;
  /* #193: @3 = 0.186085 */
  w3 = 1.8608459405645808e-01;
  /* #194: @15 = zeros(6x1) */
  casadi_clear(w15, 6);
  /* #195: @16 = 
  [[-0.707, -0.707, 0.707, 0.707, -0, -0], 
   [0.707, -0.707, 0.707, -0.707, -0, -0], 
   [-0, -0, -0, -0, -1, -1], 
   [-0.051, 0.051, -0.051, 0.051, 0.111, -0.111], 
   [-0.051, 0.051, -0.051, 0.051, -0.002, 0.002], 
   [0.167, -0.167, -0.175, 0.175, -0, -0]] */
  casadi_copy(casadi_c0, 36, w16);
  /* #196: @15 = mac(@16,@17,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w17+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #197: @6 = @15[3] */
  for (rr=(&w6), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #198: @5 = 14.8 */
  w5 = 1.4800000000000001e+01;
  /* #199: @8 = @10[2] */
  for (rr=(&w8), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #200: @5 = (@5*@8) */
  w5 *= w8;
  /* #201: @4 = -14.57 */
  w4 = -1.4570000000000000e+01;
  /* #202: @4 = (@4*@8) */
  w4 *= w8;
  /* #203: @5 = (@5-@4) */
  w5 -= w4;
  /* #204: @4 = @10[1] */
  for (rr=(&w4), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #205: @5 = (@5*@4) */
  w5 *= w4;
  /* #206: @6 = (@6-@5) */
  w6 -= w5;
  /* #207: @5 = -14.8 */
  w5 = -1.4800000000000001e+01;
  /* #208: @5 = (@5*@4) */
  w5 *= w4;
  /* #209: @7 = -12.7 */
  w7 = -1.2699999999999999e+01;
  /* #210: @7 = (@7*@4) */
  w7 *= w4;
  /* #211: @5 = (@5+@7) */
  w5 += w7;
  /* #212: @5 = (@5*@8) */
  w5 *= w8;
  /* #213: @6 = (@6-@5) */
  w6 -= w5;
  /* #214: @5 = -7.9 */
  w5 = -7.9000000000000004e+00;
  /* #215: @7 = @1[1] */
  for (rr=(&w7), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #216: @5 = (@5*@7) */
  w5 *= w7;
  /* #217: @9 = -0.12 */
  w9 = -1.2000000000000000e-01;
  /* #218: @9 = (@9*@7) */
  w9 *= w7;
  /* #219: @5 = (@5+@9) */
  w5 += w9;
  /* #220: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #221: @5 = (@5*@9) */
  w5 *= w9;
  /* #222: @6 = (@6-@5) */
  w6 -= w5;
  /* #223: @5 = -0.07 */
  w5 = -7.0000000000000007e-02;
  /* #224: @18 = -1.55 */
  w18 = -1.5500000000000000e+00;
  /* #225: @19 = @1[0] */
  for (rr=(&w19), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #226: @2 = fabs(@19) */
  w2 = casadi_fabs( w19 );
  /* #227: @18 = (@18*@2) */
  w18 *= w2;
  /* #228: @5 = (@5+@18) */
  w5 += w18;
  /* #229: @5 = (@5*@19) */
  w5 *= w19;
  /* #230: @6 = (@6+@5) */
  w6 += w5;
  /* #231: @3 = (@3*@6) */
  w3 *= w6;
  /* #232: output[0][5] = @3 */
  if (res[0]) res[0][9] = w3;
  /* #233: @3 = 0.124688 */
  w3 = 1.2468827930174564e-01;
  /* #234: @6 = @15[4] */
  for (rr=(&w6), ss=w15+4; ss!=w15+5; ss+=1) *rr++ = *ss;
  /* #235: @5 = -14.8 */
  w5 = -1.4800000000000001e+01;
  /* #236: @5 = (@5*@8) */
  w5 *= w8;
  /* #237: @18 = -14.57 */
  w18 = -1.4570000000000000e+01;
  /* #238: @18 = (@18*@8) */
  w18 *= w8;
  /* #239: @5 = (@5+@18) */
  w5 += w18;
  /* #240: @18 = @10[0] */
  for (rr=(&w18), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #241: @5 = (@5*@18) */
  w5 *= w18;
  /* #242: @6 = (@6-@5) */
  w6 -= w5;
  /* #243: @5 = 14.8 */
  w5 = 1.4800000000000001e+01;
  /* #244: @5 = (@5*@18) */
  w5 *= w18;
  /* #245: @2 = -5.5 */
  w2 = -5.5000000000000000e+00;
  /* #246: @2 = (@2*@18) */
  w2 *= w18;
  /* #247: @5 = (@5-@2) */
  w5 -= w2;
  /* #248: @5 = (@5*@8) */
  w5 *= w8;
  /* #249: @6 = (@6-@5) */
  w6 -= w5;
  /* #250: @5 = 5.2539 */
  w5 = 5.2538999999999998e+00;
  /* #251: @5 = (@5*@7) */
  w5 *= w7;
  /* #252: @8 = -0.12 */
  w8 = -1.2000000000000000e-01;
  /* #253: @8 = (@8*@19) */
  w8 *= w19;
  /* #254: @5 = (@5-@8) */
  w5 -= w8;
  /* #255: @5 = (@5*@9) */
  w5 *= w9;
  /* #256: @6 = (@6-@5) */
  w6 -= w5;
  /* #257: @5 = -0.07 */
  w5 = -7.0000000000000007e-02;
  /* #258: @8 = -1.55 */
  w8 = -1.5500000000000000e+00;
  /* #259: @19 = fabs(@7) */
  w19 = casadi_fabs( w7 );
  /* #260: @8 = (@8*@19) */
  w8 *= w19;
  /* #261: @5 = (@5+@8) */
  w5 += w8;
  /* #262: @5 = (@5*@7) */
  w5 *= w7;
  /* #263: @6 = (@6+@5) */
  w6 += w5;
  /* #264: @3 = (@3*@6) */
  w3 *= w6;
  /* #265: output[0][6] = @3 */
  if (res[0]) res[0][10] = w3;
  /* #266: @3 = 0.14245 */
  w3 = 1.4245014245014245e-01;
  /* #267: @6 = @15[5] */
  for (rr=(&w6), ss=w15+5; ss!=w15+6; ss+=1) *rr++ = *ss;
  /* #268: @5 = 14.8 */
  w5 = 1.4800000000000001e+01;
  /* #269: @5 = (@5*@4) */
  w5 *= w4;
  /* #270: @7 = -12.7 */
  w7 = -1.2699999999999999e+01;
  /* #271: @7 = (@7*@4) */
  w7 *= w4;
  /* #272: @5 = (@5-@7) */
  w5 -= w7;
  /* #273: @5 = (@5*@18) */
  w5 *= w18;
  /* #274: @6 = (@6-@5) */
  w6 -= w5;
  /* #275: @5 = -5.5 */
  w5 = -5.5000000000000000e+00;
  /* #276: @5 = (@5*@18) */
  w5 *= w18;
  /* #277: @7 = 14.8 */
  w7 = 1.4800000000000001e+01;
  /* #278: @7 = (@7*@18) */
  w7 *= w18;
  /* #279: @5 = (@5-@7) */
  w5 -= w7;
  /* #280: @5 = (@5*@4) */
  w5 *= w4;
  /* #281: @6 = (@6-@5) */
  w6 -= w5;
  /* #282: @5 = -0.07 */
  w5 = -7.0000000000000007e-02;
  /* #283: @4 = -1.55 */
  w4 = -1.5500000000000000e+00;
  /* #284: @7 = fabs(@9) */
  w7 = casadi_fabs( w9 );
  /* #285: @4 = (@4*@7) */
  w4 *= w7;
  /* #286: @5 = (@5+@4) */
  w5 += w4;
  /* #287: @5 = (@5*@9) */
  w5 *= w9;
  /* #288: @6 = (@6+@5) */
  w6 += w5;
  /* #289: @3 = (@3*@6) */
  w3 *= w6;
  /* #290: output[0][7] = @3 */
  if (res[0]) res[0][11] = w3;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_3d_acados_mpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_3d_acados_mpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_3d_acados_mpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_3d_acados_mpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_3d_acados_mpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_3d_acados_mpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_3d_acados_mpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_3d_acados_mpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_3d_acados_mpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_3d_acados_mpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_3d_acados_mpc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_3d_acados_mpc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_3d_acados_mpc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_3d_acados_mpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_3d_acados_mpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_3d_acados_mpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 97;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
